### ISSUE TITLE
Config doesn't handle negative coordinates

### ISSUE THREAD

**Issue by adammhaile** [ManiacalLabs/SimPixel#1]
Actually... I think what happens is that the values roll over to near the max 16 bit unsigned value so that pixels render, just WAY off center.
Should be easy fix, as it is currently being cast to a Uint16 array: https://github.com/ManiacalLabs/WebVis/blob/a88f23d11d9488f8210cf2e77e9ed706fbde7a7b/src/js/network.js#L32
I updated BP to send it as signed, so should just need to change this.

**Comment by adammhaile** [comment]
@mwcz  Switched to using Int16 for coords array and now it works fine.

**Comment by mwcz** [comment]
+1 c'est bon
